---
# redis setting
- name: Add Redis repository
  apt_repository:
    repo: 'ppa:chris-lea/redis-server'
    state: present
    update_cache: 'yes'

- name: Install Redis
  apt:
    pkg: redis-server
    state: latest
    update_cache: 'yes'
    # cache_valid_time: {{aptcachetime}}

- name: Configure Redis
