---
# Install mongodb
- name: install mongodb repository
  apt_repository:
    repo: "deb {{ mongodb_apt_repo }}"
    state: "present"
    update_cache: "yes"

- name: install mongodb
  apt:
    name: "mongodb-org"
    state: "present"

- name: create mongodb data directory
  file:
    path: "{{ mongodb_db_path }}"
    state: directory
    mode: 0755
    owner: mongodb
    group: mongodb
