---
# install node
- name: Installing apt-key
  apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key
           state=present

- name: Import the NodeSource GPG key into apt
  apt_key: url=https://deb.nodesource.com/gpgkey/nodesource.gpg.key
           state=present

- name: Add NodeSource deb repository

- name: Add NodeSource deb-src repository

- name: Install Node.js
  apt: pkg=nodejs state=latest update_cache=yes
